### ISSUE TITLE
如何保证 usb.json 的完整性

### ISSUE THREAD

**Issue by littledu** [Curtion/Web-SerialPort#1]
请教一下，usb.json 需要去哪里找来更新，比如连接了一个新的设备，设备的 devid 不存在于 usb.json 中，搜了相关的厂家信息，也不知道如何找到这个 devid

**Comment by Curtion** [comment]
这是通过脚本爬取 https://devicehunt.com/all-usb-vendors 网站获取到的数据(现在已经无法找到该脚本了)，json的格式是我自定义的。 如果json文件中没有厂家的相关信息，可以尝试使用 http://www.linux-usb.org/usb.ids 的数据

**Comment by littledu** [comment]
@Curtion 感谢感谢，神奇的是我这个设备居然在这两个网站里面都搜不到，能搜到 vendor，却没有对应的 devid

**Comment by Curtion** [comment]
> @Curtion 感谢感谢，神奇的是我这个设备居然在这两个网站里面都搜不到，能搜到 vendor，却没有对应的 devid

这个可能是国内很多厂商的USB设备应该没有更新上去，目前为止我也没有找到更好的数据库。

**Comment by littledu** [comment]
@Curtion 好嗒，感谢感谢
