### ISSUE TITLE
有没有什么办法能知道当前的串口号是多少?比如图中的COM4

### ISSUE THREAD

**Issue by mimimiaomiao1** [Curtion/Web-SerialPort#2]
<img width="278" alt="image" src="https://user-images.githubusercontent.com/58240619/209521867-eb2fe788-22f5-4faa-8ca4-4680a2605606.png">
<img width="706" alt="image" src="https://user-images.githubusercontent.com/58240619/209521944-1370873c-9b83-44de-8df2-cd55afb4ceb3.png">

**Comment by mimimiaomiao1** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/58240619/209522056-d8a50eca-b413-46d5-98d0-5d03c1d3d1c9.png">
应该用哪个方法,能否指导一下.谢谢.

**Comment by Curtion** [comment]
这个值应该是暂时没有办法取到，我也没有找到相应的方法
